---
- name: WaddleBot
  hosts: localhost
  connection: local
  vars_files:
    - vars/base.yml
  become: true
  become_user: root
  remote_user: root
  tasks:
     - name: Build
      tags:
        - build
      include_tasks:
        file: "jobs/build/{{ item }}.yml"
        apply:
          tags: build
      loop:
        - build
    - name: Run And Configure
      tags:
        - run
      include_tasks:
        file: jobs/run/{{ item }}.yml
        apply:
          tags: run
      loop:
        - run
    - name: Execute application
      include_tasks:
        file: jobs/run/exec.yml
    - name: Run execution status tests to make sure app is running as expected
      include_tasks:
        file: jobs/tests/tests.yml

