---
- name: Generate discord config fragment
  ansible.builtin.template:
    src: "{{playbook_dir}}/templates/discord.j2"
    dest: "/etc/{{ app.title }}"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
  when: discord.enable == "1"

- name: Generate twitch config fragment
  ansible.builtin.template:
    src: "{{playbook_dir}}/templates/twitch.j2"
    dest: "/etc/{{ app.title }}"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
  when: twitch.enable == "1"

- name: Assemble from fragment configs from a directory
  ansible.builtin.assemble:
    src: "/etc/{{ app.title }}"
    dest: "/etc/{{ app.title }}/matterbridge.toml"
    owner: "{{ run.user }}"
    group: "{{ run.user }}"
